version: "3"
services:
  app:
    build: ./
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.30 
    ports:
      - "3000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:roi
